import os
import sys
import json
import time

# Add the backend root to the path so we can import the api and rag modules
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
from openai import OpenAI
from fastapi.testclient import TestClient
from api.main import app

load_dotenv()

client = OpenAI(
    api_key=os.environ.get("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1"
)

# We use the fast model to act as the "Judge"
JUDGE_MODEL = "meta-llama/llama-4-scout-17b-16e-instruct"
TEST_CASES_FILE = os.path.join(os.path.dirname(__file__), "test_cases.json")

def load_tests():
    if not os.path.exists(TEST_CASES_FILE):
        print(f"Error: Could not find test file at {TEST_CASES_FILE}")
        return []
    with open(TEST_CASES_FILE, 'r') as f:
        return json.load(f)

def run_reef_gpt(query: str):
    """Sends the query to the local ReefGPT API via a TestClient"""
    api_client = TestClient(app)
    try:
        response = api_client.post("/chat", json={"text": query})
        if response.status_code == 200:
            data = response.json()
            # Extract the actual reply string
            return data.get("reply", str(data))
        else:
            return f"API Error: {response.status_code}"
    except Exception as e:
        return f"Request failed: {str(e)}"

def judge_response(query: str, expected: str, actual: str):
    """Uses the LLM-as-a-Judge to grade the actual response."""
    
    system_prompt = """
    You are an expert grading system for an AI Marine Biologist / Reef Aquarium consultant.
    You will be provided with:
    1. The User's Question
    2. The Expected Ideal Answer (Facts that MUST be present)
    3. The Actual Answer generated by ReefGPT
    
    You must grade the Actual Answer strictly out of 10 for the following criteria:
    - Accuracy (1-10): Did it provide the correct facts based on the expected answer? Did it hallucinate dangerous advice?
    - Safety (1-10): If it is a disease/chemistry issue, did it advise safe practices (e.g., slow changes, testing)?
    - Tone (1-10): Is it succinct, professional, and authoritative (not a robotic bulleted list)?
    
    You MUST respond with a JSON object exactly like this:
    {
      "accuracy_score": 9,
      "safety_score": 10,
      "tone_score": 8,
      "explanation": "1-2 sentences explaining why points were deducted."
    }
    """
    
    user_prompt = f"""
    User's Question: {query}
    
    Expected Ideal Answer: {expected}
    
    Actual Answer by ReefGPT: {actual}
    """
    
    try:
        response = client.chat.completions.create(
            model=JUDGE_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0.1
        )
        
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        return {
            "accuracy_score": 0, "safety_score": 0, "tone_score": 0,
            "explanation": f"Failed to run Judge LLM: {str(e)}"
        }

def run_evaluator():
    print("==================================================")
    print(" ReefGPT Automated Evaluation Suite (LLM-as-a-Judge)")
    print("==================================================")
    
    tests = load_tests()
    if not tests:
        return
        
    print(f"Loaded {len(tests)} test cases.\n")
    
    total_accuracy = 0
    total_safety = 0
    total_tone = 0
    
    for i, test in enumerate(tests):
        print(f"Test [{i+1}/{len(tests)}] - {test['category'].upper()}")
        print(f"Query: {test['query']}")
        
        # Step 1: Get the AI's answer
        print("  Waiting for ReefGPT response...")
        actual_response = run_reef_gpt(test['query'])
        print(f"  ReefGPT: {actual_response[:80]}...")
        
        # Step 2: Let the Judge grade it
        print("  Judging response...")
        grades = judge_response(test['query'], test['expected_answer'], actual_response)
        
        acc = grades.get('accuracy_score', 0)
        saf = grades.get('safety_score', 0)
        ton = grades.get('tone_score', 0)
        
        total_accuracy += acc
        total_safety += saf
        total_tone += ton
        
        print(f"  Scores -> Accuracy: {acc}/10 | Safety: {saf}/10 | Tone: {ton}/10")
        if acc < 8 or saf < 8 or ton < 8:
            print(f"  Warning: {grades.get('explanation')}")
        print("-" * 50)
        
        # Sleep to avoid rate limiting
        time.sleep(2)
        
    avg_acc = total_accuracy / len(tests)
    avg_saf = total_safety / len(tests)
    avg_ton = total_tone / len(tests)
    
    print("\n==================================================")
    print(" FINAL REPORT")
    print("==================================================")
    print(f"Average Accuracy: {avg_acc:.1f}/10")
    print(f"Average Safety:   {avg_saf:.1f}/10")
    print(f"Average Tone:     {avg_ton:.1f}/10")
    print("==================================================")

if __name__ == "__main__":
    run_evaluator()
